### ISSUE TITLE
Add Modal Backdrop Overlay for Prediction Results Display

### ISSUE THREAD

**Issue by LokeshPatil-loki** [LokeshPatil-loki/hadoop-ml#1]
### Description
Our diabetes prediction application currently displays results in a basic modal window that lacks modern UI/UX features. The modal implementation needs enhancement to meet current web application standards and improve user experience.

### Current Behavior
Currently, the prediction results are shown in a modal without a proper backdrop overlay. The modal doesn't have a click-outside-to-close functionality, making the user experience less intuitive.

### Desired Behavior
- Add a semi-transparent backdrop overlay when the modal is open
- Implement click-outside-to-close functionality
- Add smooth animations for modal open/close transitions
- Improve modal styling and accessibility

**Comment by manishlase** [comment]
I can fix this by using a mix of CSS and JavaScript to achieve this and ensure improved styling and accessibility.
