### ISSUE TITLE
Change Provisioning Type from Inline Shell to Path-Based Shell Script

### ISSUE THREAD

**Issue by LokeshPatil-loki** [LokeshPatil-loki/hadoop-ml#3]
**Description:**
We need to move the current inline shell provisioning in the Vagrantfile to a path-based shell script for better readability and maintainability. The existing shell commands should be relocated to a separate `setup.sh` file, and the Vagrantfile should reference this external script. This change will make it easier to manage the provisioning process and allow for future enhancements to the provisioning script without cluttering the Vagrantfile.

**Tasks:**
1. Create a new `setup.sh` file in the root directory of the project.
2. Move the existing inline shell commands from the Vagrantfile to `setup.sh`.
3. Update the Vagrantfile to use a path-based shell provisioner referencing `setup.sh`.
4. Test the provisioning process to ensure it works as expected.

**Comment by dikshita1920** [comment]
I would like to work on this perticular issue
